steps:
  - id: Install
    name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    env: 
    - 'NPM_TOKEN=${_NPM_TOKEN}'
  - id: Build
    name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    env: 
    - 'NPM_TOKEN=${_NPM_TOKEN}' 
  - id: Deploy
    name: gcr.io/cloud-builders/gsutil
    args: ['cp', '-r', './public/static', './public/app-*', './public/index.html', 'gs://cloud_build_testing/']
  - id: Remove Old Version
    name: gcr.io/cloud-builders/gsutil
    args: ['rm', 'gs://cloud_build_testing/app-${_OLD_VERSION}*']
substitutions:
options:
    substitution_option: 'ALLOW_LOOSE'